---
- debug: var=aliyun_region
- name: Create the Aliyun ECS security group
  alicloud_security_group:
    group_name: "{{ aliyun_security_group }}"
    description: Security group for Streisand
    alicloud_region: "{{ aliyun_region }}"
    vpc_id: "{{ aliyun_vpc_id | default(omit) }}"
    alicloud_access_key: "{{ aliyun_access_key }}"
    alicloud_secret_key: "{{ aliyun_secret_key }}"

- name: Pause for fifteen seconds to ensure the Aliyun ECS security group has been created
  pause:
    seconds: 15

- name: Open necessary ports across supported services in the Aliyun ECS security group
  alicloud_security_group:
    group_name: "{{ aliyun_security_group }}"
    description: Security group for Streisand
    alicloud_region: "{{ aliyun_region }}"
    vpc_id: "{{ aliyun_vpc_id | default(omit) }}"
    alicloud_access_key: "{{ aliyun_access_key }}"
    alicloud_secret_key: "{{ aliyun_secret_key }}"
    rules:
      # Nginx
      # ---
      - ip_protocol: tcp
        port_range: "{{ nginx_port }}/{{ nginx_port }}"
        source_cidr_ip: 0.0.0.0/0
      # SSH
      # ---
      - ip_protocol: tcp
        port_range: "{{ ssh_port }}/{{ ssh_port }}"
        source_cidr_ip: 0.0.0.0/0
      # HTTP (Let's Encrypt)
      # ---
      - ip_protocol: tcp
        port_range: "{{ le_port }}/{{ le_port }}"
        source_cidr_ip: 0.0.0.0/0
    rules_egress:
      - proto: all
        port_range: 1/65535
        source_cidr_ip: 0.0.0.0/0

# L2TP/IPsec
# ---
- name: Open the L2TP/IPsec ports in the Aliyun ECS security group
  alicloud_security_group:
    group_name: "{{ aliyun_security_group }}"
    description: Security group for Streisand
    alicloud_region: "{{ source_cidr_ip }}"
    vpc_id: "{{ aliyun_vpc_id | default(omit) }}"
    alicloud_access_key: "{{ aliyun_access_key }}"
    alicloud_secret_key: "{{ aliyun_secret_key }}"
    purge_rules: no
    purge_rules_egress: no
    rules:
      - ip_protocol: udp
        port_range: "500/500"
        source_cidr_ip: 0.0.0.0/0
      - ip_protocol: udp
        port_range: "4500/4500"
        source_cidr_ip: 0.0.0.0/0
      - ip_protocol: udp
        port_range: "1701/1701"
        source_cidr_ip: 0.0.0.0/0
  when: streisand_l2tp_enabled

# OpenConnect
# ---
- name: Open the OpenConnect ports in the ECS security group
  alicloud_security_group:
    group_name: "{{ aliyun_security_group }}"
    description: Security group for Streisand
    alicloud_region: "{{ source_cidr_ip }}"
    vpc_id: "{{ aliyun_vpc_id | default(omit) }}"
    alicloud_access_key: "{{ aliyun_access_key }}"
    alicloud_secret_key: "{{ aliyun_secret_key }}"
    purge_rules: no
    purge_rules_egress: no
    rules:
      # OpenConnect TCP
      # ---
      - ip_protocol: tcp
        port_range: "{{ ocserv_port }}/{{ ocserv_port }}"
        source_cidr_ip: 0.0.0.0/0
      # OpenConnect UDP
      # ---
      - ip_protocol: udp
        port_range: "{{ ocserv_port }}/{{ ocserv_port }}"
        source_cidr_ip: 0.0.0.0/0
  when: streisand_openconnect_enabled

# OpenVPN
# ---
- name: Open the OpenVPN ports in the ECS security group
  alicloud_security_group:
    group_name: "{{ aliyun_security_group }}"
    description: Security group for Streisand
    alicloud_region: "{{ source_cidr_ip }}"
    vpc_id: "{{ aliyun_vpc_id | default(omit) }}"
    alicloud_access_key: "{{ aliyun_access_key }}"
    alicloud_secret_key: "{{ aliyun_secret_key }}"
    purge_rules: no
    purge_rules_egress: no
    rules:
      # OpenVPN TCP
      # ---
      - ip_protocol: tcp
        port_range: "{{ openvpn_port }}/{{ openvpn_port }}"
        source_cidr_ip: 0.0.0.0/0
      # OpenVPN UDP
      # ---
      - ip_protocol: udp
        port_range: "{{ openvpn_port_udp }}/{{ openvpn_port_udp }}"
        source_cidr_ip: 0.0.0.0/0
  when: streisand_openvpn_enabled

# stunnel
# ---
- name: Open the stunnel port in the ECS security group
  alicloud_security_group:
    group_name: "{{ aliyun_security_group }}"
    description: Security group for Streisand
    alicloud_region: "{{ source_cidr_ip }}"
    vpc_id: "{{ aliyun_vpc_id | default(omit) }}"
    alicloud_access_key: "{{ aliyun_access_key }}"
    alicloud_secret_key: "{{ aliyun_secret_key }}"
    purge_rules: no
    purge_rules_egress: no
    rules:
      # Stunnel
      # ---
      - ip_protocol: tcp
        port_range: "{{ stunnel_remote_port }}/{{ stunnel_remote_port }}"
        source_cidr_ip: 0.0.0.0/0
  when: streisand_openvpn_enabled and streisand_stunnel_enabled

# Shadowsocks
# ---
- name: Open the Shadowsocks ports in the ECS security group
  alicloud_security_group:
    group_name: "{{ aliyun_security_group }}"
    description: Security group for Streisand
    alicloud_region: "{{ source_cidr_ip }}"
    vpc_id: "{{ aliyun_vpc_id | default(omit) }}"
    alicloud_access_key: "{{ aliyun_access_key }}"
    alicloud_secret_key: "{{ aliyun_secret_key }}"
    purge_rules: no
    purge_rules_egress: no
    rules:
      # Shadowsocks TCP
      # ---
      - ip_protocol: tcp
        port_range: "{{ shadowsocks_server_port }}/{{ shadowsocks_server_port }}"
        source_cidr_ip: 0.0.0.0/0
      # Shadowsocks UDP
      # ---
      - ip_protocol: udp
        port_range: "{{ shadowsocks_server_port }}/{{ shadowsocks_server_port }}"
        source_cidr_ip: 0.0.0.0/0
  when: streisand_shadowsocks_enabled

# Tor
# ---
- name: Open the Tor ports in the ECS security group
  alicloud_security_group:
    group_name: "{{ aliyun_security_group }}"
    description: Security group for Streisand
    alicloud_region: "{{ source_cidr_ip }}"
    vpc_id: "{{ aliyun_vpc_id | default(omit) }}"
    alicloud_access_key: "{{ aliyun_access_key }}"
    alicloud_secret_key: "{{ aliyun_secret_key }}"
    purge_rules: no
    purge_rules_egress: no
    rules:
      # Tor
      # ---
      - ip_protocol: tcp
        port_range: "{{ tor_orport }}/{{ tor_orport }}"
        source_cidr_ip: 0.0.0.0/0
      # Tor obfs4
      # ---
      - ip_protocol: tcp
        port_range: "{{ tor_obfs4_port }}/{{ tor_obfs4_port }}"
        source_cidr_ip: 0.0.0.0/0
  when: streisand_tor_enabled

# WireGuard
# ---
- name: Open the WireGuard ports in the ECS security group
  alicloud_security_group:
    group_name: "{{ aliyun_security_group }}"
    description: Security group for Streisand
    alicloud_region: "{{ source_cidr_ip }}"
    vpc_id: "{{ aliyun_vpc_id | default(omit) }}"
    alicloud_access_key: "{{ aliyun_access_key }}"
    alicloud_secret_key: "{{ aliyun_secret_key }}"
    purge_rules: no
    purge_rules_egress: no
    rules:
      - ip_protocol: udp
        port_range: "{{ wireguard_port }}/{{ wireguard_port }}"
        source_cidr_ip: 0.0.0.0/0
  when: streisand_wireguard_enabled
